import re

with open('c:/Users/Victus/Antigrav/BioWeb/app.js', 'r', encoding='utf-8') as f:
    js = f.read()

new_translations = '''    const translations = {
        id: {
            "nav.home": "Beranda",
            "nav.bio": "Biodata",
            "nav.skills": "Keahlian",
            "nav.experience": "Pengalaman",
            "nav.portfolio": "Portofolio",
            "nav.contact": "Kontak",
            "nav.editBio": "Edit Bio",
            "nav.printCv": "Cetak CV",
            "hero.greeting": "Halo, Selamat Datang di Bio Profil Saya",
            "hero.typingPrefix": "Saya seorang ",
            "hero.degree": "Teknik Informatika",
            "hero.ctaContact": "Hubungi Saya",
            "hero.ctaBio": "Lihat Biodata Lengkap",
            "stats.exp": "Tahun Pengalaman",
            "stats.projects": "Proyek Selesai",
            "stats.clients": "Klien Puas",
            "stats.quality": "% Komitmen Kualitas",
            "section.bio.tag": "Profil Informasi",
            "section.bio.title1": "Biodata",
            "section.bio.title2": "Diri Lengkap",
            "section.bio.subtitle": "Rincian identitas pribadi, informasi kontak, latar belakang, dan hobi kegemaran.",
            "bio.card1.title": "Identitas Pribadi",
            "bio.label.fullname": "Nama Lengkap",
            "bio.label.nickname": "Nama Panggilan",
            "bio.label.pobdob": "Tempat, Tgl Lahir",
            "bio.label.gender": "Jenis Kelamin",
            "bio.label.religion": "Agama",
            "bio.label.nationality": "Kewarganegaraan",
            "bio.card2.title": "Kontak & Domisili",
            "bio.label.email": "Email Utama",
            "bio.label.phone": "Nomor Telepon / WA",
            "bio.label.address": "Alamat Lengkap",
            "bio.label.marital": "Status Perkawinan",
            "bio.label.job": "Pekerjaan Saat Ini",
            "bio.label.website": "Website Personal",
            "bio.card3.title": "Minat & Hobi",
            "bio.card3.subtitle": "Penguasaan Bahasa",
            "lang.id": "Bahasa Indonesia",
            "lang.en": "Bahasa Inggris",
            "section.skills.tag": "Kemampuan Teknis",
            "section.skills.title1": "Keahlian &",
            "section.skills.title2": "Kompetensi",
            "filter.all": "Semua Skill",
            "section.skills.subtitle": "Teknologi dan keterampilan yang saya kuasai dalam pengembangan perangkat lunak.",
            "skill.soft.title": "Problem Solving & Adaptabilitas",
            "skill.soft.desc": "Analisis Masalah, Pemikiran Kritis, Komunikasi Tim, Manajemen Waktu, Fast Learning.",
            "section.timeline.tag": "Rekam Jejak",
            "section.timeline.title1": "Pengalaman &",
            "section.timeline.title2": "Pendidikan",
            "section.timeline.subtitle": "Perjalanan karier profesional dan latar belakang akademis saya.",
            "timeline.now": "2024 - Sekarang",
            "timeline.desc1": "Memimpin tim frontend dalam mengembangkan aplikasi manajemen cloud enterprise skala besar, meningkatkan kecepatan muat sebesar 40%, dan mengimplementasikan arsitektur micro-frontend.",
            "timeline.desc2": "Merancang wireframe, prototype interaktif di Figma, dan mengimplementasikannya menjadi kode HTML/CSS/JS yang responsif serta ramah SEO untuk lebih dari 20 klien startup.",
            "timeline.desc3": "Lulus dengan predikat Cum Laude (IPK 3.85/4.00). Aktif di Organisasi Himpunan Mahasiswa Informatika dan ketua divisi Web & Publication.",
            "timeline.desc4": "Menyelesaikan sertifikasi intensif dalam keahlian arsitektur cloud, keamanan web OWASP, dan pengujian performa tinggi.",
            "section.portfolio.tag": "Galeri Proyek",
            "section.portfolio.title1": "Portofolio",
            "section.portfolio.title2": "Karya Pilihan",
            "section.portfolio.subtitle": "Beberapa hasil karya aplikasi web dan sistem yang telah saya kembangkan.",
            "port.title1": "Sistem Kasir Cloud (Smart POS)",
            "port.desc1": "Aplikasi kasir multi-outlet dengan fitur inventaris real-time, laporan penjualan grafik, dan integrasi pembayaran QRIS.",
            "port.desc2": "Dashboard pemantauan performa bisnis secara interaktif dengan sistem notifikasi pintar dan visualisasi data tinggi.",
            "port.desc3": "Aplikasi pengelola keuangan pribadi dengan pencatatan otomatis, kalkulator target tabungan, dan ekspor laporan bulanan.",
            "port.demo": "Demo Live",
            "port.source": "Source",
            "section.contact.tag": "Terhubung",
            "section.contact.title1": "Hubungi",
            "section.contact.title2": "Saya",
            "section.contact.subtitle": "Tertarik bekerjasama atau ingin bertanya sesuatu? Silakan kirimkan pesan di bawah ini.",
            "contact.info.title": "Informasi Kontak",
            "contact.info.desc": "Jangan ragu untuk menghubungi saya melalui kontak berikut atau formulir langsung.",
            "contact.label.email": "Email Direct",
            "contact.label.wa": "WhatsApp Chat",
            "contact.label.loc": "Lokasi Saat Ini",
            "contact.btn.wa": "Kirim Pesan via WhatsApp Instant",
            "contact.form.name": "Nama Anda",
            "contact.form.email": "Alamat Email",
            "contact.form.subject": "Subjek Pesan",
            "contact.form.message": "Isi Pesan",
            "contact.btn.submit": "Kirim Pesan Sekarang",
            "footer.copy": "&copy; 2026 Rizky Ramadhan. Hak Cipta Dilindungi. Dibuat dengan Warna Cerah & Animasi Interaktif."
        },
        en: {
            "nav.home": "Home",
            "nav.bio": "Biography",
            "nav.skills": "Skills",
            "nav.experience": "Experience",
            "nav.portfolio": "Portfolio",
            "nav.contact": "Contact",
            "nav.editBio": "Edit Bio",
            "nav.printCv": "Print CV",
            "hero.greeting": "Hello, Welcome to My Bio Profile",
            "hero.typingPrefix": "I am a ",
            "hero.degree": "Informatics Engineering",
            "hero.ctaContact": "Contact Me",
            "hero.ctaBio": "View Full Bio",
            "stats.exp": "Years Experience",
            "stats.projects": "Projects Completed",
            "stats.clients": "Satisfied Clients",
            "stats.quality": "% Quality Commitment",
            "section.bio.tag": "Profile Information",
            "section.bio.title1": "Complete",
            "section.bio.title2": "Biography",
            "section.bio.subtitle": "Personal identity details, contact information, background, and hobbies.",
            "bio.card1.title": "Personal Identity",
            "bio.label.fullname": "Full Name",
            "bio.label.nickname": "Nickname",
            "bio.label.pobdob": "Place, Date of Birth",
            "bio.label.gender": "Gender",
            "bio.label.religion": "Religion",
            "bio.label.nationality": "Nationality",
            "bio.card2.title": "Contact & Domicile",
            "bio.label.email": "Main Email",
            "bio.label.phone": "Phone / WA Number",
            "bio.label.address": "Full Address",
            "bio.label.marital": "Marital Status",
            "bio.label.job": "Current Job",
            "bio.label.website": "Personal Website",
            "bio.card3.title": "Interests & Hobbies",
            "bio.card3.subtitle": "Language Proficiency",
            "lang.id": "Indonesian",
            "lang.en": "English",
            "section.skills.tag": "Technical Skills",
            "section.skills.title1": "Skills &",
            "section.skills.title2": "Competencies",
            "filter.all": "All Skills",
            "section.skills.subtitle": "Technologies and skills I have mastered in software development.",
            "skill.soft.title": "Problem Solving & Adaptability",
            "skill.soft.desc": "Problem Analysis, Critical Thinking, Team Communication, Time Management, Fast Learning.",
            "section.timeline.tag": "Track Record",
            "section.timeline.title1": "Experience &",
            "section.timeline.title2": "Education",
            "section.timeline.subtitle": "My professional career journey and academic background.",
            "timeline.now": "2024 - Present",
            "timeline.desc1": "Led the frontend team in developing a large-scale enterprise cloud management application, improving load speed by 40%, and implementing micro-frontend architecture.",
            "timeline.desc2": "Designed wireframes, interactive prototypes in Figma, and implemented them into responsive, SEO-friendly HTML/CSS/JS code for over 20 startup clients.",
            "timeline.desc3": "Graduated with Cum Laude honors (GPA 3.85/4.00). Active in the Informatics Student Association and head of the Web & Publication division.",
            "timeline.desc4": "Completed intensive certification in cloud architecture, OWASP web security, and high-performance testing.",
            "section.portfolio.tag": "Project Gallery",
            "section.portfolio.title1": "Selected",
            "section.portfolio.title2": "Portfolio",
            "section.portfolio.subtitle": "Some of the web applications and systems I have developed.",
            "port.title1": "Cloud POS System (Smart POS)",
            "port.desc1": "Multi-outlet cashier application with real-time inventory, graphical sales reports, and QRIS payment integration.",
            "port.desc2": "Interactive business performance monitoring dashboard with smart notification system and rich data visualization.",
            "port.desc3": "Personal finance management application with automatic recording, savings target calculator, and monthly report export.",
            "port.demo": "Live Demo",
            "port.source": "Source",
            "section.contact.tag": "Get in Touch",
            "section.contact.title1": "Contact",
            "section.contact.title2": "Me",
            "section.contact.subtitle": "Interested in working together or have a question? Feel free to send a message below.",
            "contact.info.title": "Contact Information",
            "contact.info.desc": "Don't hesitate to reach out to me via the following contacts or the direct form.",
            "contact.label.email": "Direct Email",
            "contact.label.wa": "WhatsApp Chat",
            "contact.label.loc": "Current Location",
            "contact.btn.wa": "Send Message via Instant WhatsApp",
            "contact.form.name": "Your Name",
            "contact.form.email": "Email Address",
            "contact.form.subject": "Message Subject",
            "contact.form.message": "Message Body",
            "contact.btn.submit": "Send Message Now",
            "footer.copy": "&copy; 2026 Rizky Ramadhan. All Rights Reserved. Built with Vibrant Colors & Interactive Animations."
        }
    };'''

# Replace the translations object
js = re.sub(r'const translations = \{.*?    \};\n', new_translations + '\n', js, flags=re.DOTALL)

with open('c:/Users/Victus/Antigrav/BioWeb/app.js', 'w', encoding='utf-8') as f:
    f.write(js)
